### ISSUE TITLE
[DOC]: Issue Open Add Comment WF

### ISSUE THREAD

**Issue by developer-lfdsystems** [lfdsystems/workflows-testing#7]

**Comment by admin-lfdsystems** [comment]
**developer-lfdsystems**

Thank you for submitting an Issue.

Please make sure you have provided as much context as possible.

We will review this as soon as possible.

We will keep you posted with the progress.

>[!Warning]
>_If you make any changes to the Issue's body or title, the review process will be reset and the Issue will be moved back to the NEW state.

**Comment by developer-lfdsystems** [comment]
This has worked as expected
